[clean-logs]
# Print out all phrases and regex to be filtered out on startup
printOnStart = true

# Print a single line on start saying that Clean Logs will filter from this point forward
printInitLineOnStart = false

# If a log message has one of these phrases, it will be filtered out from logging
phrases = []

# If a log message matches one of these regex patterns, it will be filtered out from logging
regex = []
