name: Release
on: [ workflow_dispatch ]

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
      - run: ./gradlew shadowJar modrinth # publish -- maven is currently down
        env:
          MODRINTH: ${{ secrets.MODRINTH }}
          MAVEN_URL: "https://maven.waffle.coffee/releases"
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
          SNAPSHOT: ""
