name: Snapshot Publish
on:
  push:
    branches:
      - main

jobs:
  snapshot_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
      - run: ./gradlew publish
        env:
          MAVEN_URL: "https://maven.waffle.coffee/snapshots"
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
          SNAPSHOT: "-SNAPSHOT"
